### ISSUE TITLE
How to add click event for stacked column bar chart

### ISSUE THREAD

**Issue by bandarumurali** [predixdesignsystem/px-vis-bar-chart#2]
Can anyone let me know, what is the event that we need to bind to get the type of bar segment clicked.
![exec](https://user-images.githubusercontent.com/20990014/40617900-61c74164-62ad-11e8-9502-eddc7b4fa86f.JPG)

When I click on any segment of the bar, for example when i click on 2017 Q1 segment i need data specifying that 2017 Q1 was clicked, so that i can use that data for further actions like passing clicked data to ajax calls.

Appreciate your help.
@nonmetalhail @benoitjchevalier Can you help me in finding out the event for the above query?

**Comment by nonmetalhail** [comment]
Neither of us work on nor support Predix anymore. Good luck.

**Comment by jimdefrisco** [comment]
There is no out-of-the-box option that accomplishes what you want. There is an actionConfig property that is used to set up actions for a variety of standard mouse interactions (like zoom). You might take a look at that (see px-vis-interaction-space and the _setupRegularActions method in px-vis-behavior-common) to define some custom actions.
