### ISSUE TITLE
px-vis-bar-chart is not working with polymer 1 version

### ISSUE THREAD

**Issue by sravanmca21** [predixdesignsystem/px-vis-bar-chart#3]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
Once you've created your code example, you can save it under a new url.
Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by sravanmca21** [comment]
I am trying to install bar chart in px-web-app-starter project, It is giving below error.
px-view.html:280 Uncaught TypeError: nodes.forEach is not a function
    at HTMLElement._removeAllElements (px-view.html:280)

**Comment by jimdefrisco** [comment]
The bar chart is a Polymer2 only component, from my understanding.
