### ISSUE TITLE
Error on resize when hideRegister starts off as 'true'

### ISSUE THREAD

**Issue by Asheq** [predixdesignsystem/px-vis-bar-chart#4]
## Steps to reproduce the problem:

Clone the project and run the demo with `gulp serve`

In `demo/px-vis-bar-chart-demo.html`, change `preventResize` to false and `hideRegister` to true:
![image](https://user-images.githubusercontent.com/4657140/44681677-45f95680-aa0f-11e8-82d9-c65abe57d7a2.png)

On the demo page (on http://localhost:8080), observe that the charts fail to resize in response to a browser resize. The reason seems to be an error in _resizeCalculations:
![image](https://user-images.githubusercontent.com/4657140/44681737-77722200-aa0f-11e8-8254-6787224179d4.png)

The element with id "register" is never stamped into the DOM and therefore the output of querySelector returns null.

## Environment:

Component version: 1.0.2
OS: Mac

Thanks for your help!

**Comment by jimdefrisco** [comment]
Thanks for the report - yeah, looks like the _resizeCalculation code assumes the register is present. Feel free to follow the process for opening a [pull request](https://www.predix-ui.com/#/develop/contribution) to submit your fix.
